# Site settings
title: Person-who-does-stuff
email: cm0215@uah.edu
url: https://github.com/jeromelachaud/freelancer-theme
description: "It's a description"
keywords: "your keywords, separated by commas"
skills: "See, Do, Become"
meta_author: McKinney Connor

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Connor McKinney
  location: Address
  social: Around the Web

repository : ConnorMcKinney/ConnorMcKinney.github.io

a: &github_url "https://github.com/ConnorMcKinney"
b: &linkedin_url "https://www.linkedin.com/in/connor-mckinney/"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: GitHub
    url: *github_url
    icon: "fab fa-fw fa-github" 
  - title: LinkedIn
    url: *linkedin_url
    icon: "fab fa-linkedin"

# Postal address (add as many lines as necessary)
address:
  - line: 533 Ben Avenue SW
  - line: Lilburn, GA 30047

contact_information:
   - line: Connor McKinney
   - line: 770-330-138
   - line: cm0215@uah.edu


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
